<strategy> ::= lambda h, i: <fixed> | lambda h, i: <adaptive>
<fixed> ::= <varying>[i] | <dove> | <hawk>
<varying> ::= [<choice>, <choice>, <choice>, <choice>]
<hawk> ::= "H"
<dove> ::= "D"
<adaptive> ::= <choice> if h[i] == <choice> else <choice>
<choice> ::= "H" | "D"