<strategy> ::= lambda h, i: <fixed> | lambda h, i: <adaptive>
<fixed> ::= <varying>[i] | <cooperate> | <defect>
<varying> ::= [<choice>, <choice>, <choice>, <choice>]
<cooperate> ::= ["C"]
<defect> ::= ["D"]
<adaptive> ::= <choice> if h[i][0] == <choice> else <choice>
<choice> ::= "C" | "D"